### ISSUE TITLE
Can we add more code owners to this repo?

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/platform-services-status-page-notifications#10]
It looks like the CODEOWNERS file is trying to include the team https://github.com/BCDevOps/platform-services-status-page-notifications/blob/master/.github/CODEOWNERS but it's not correctly allowing them all to approve the merge.

This link seems to suggest the team needs write access to the repo for it to work properly https://github.community/t5/How-to-use-Git-and-GitHub/CODEOWNERS-works-with-users-but-not-teams/td-p/4986

**Comment by stewartshea** [comment]
It actually looked like we may have had a different team on the codeowners file, it was devops-team-services and not platform-operations. This has been updated. @sbarre-esit are you able to test?

**Comment by sbarre-esit** [comment]
#13 looks like it included platform ops as a codeowner, thanks
